/**
 * Seeded Tags — platform-generated discovery tags for Happy Hour Compass.
 *
 * OWNERSHIP MODEL
 * ───────────────
 * search_tags  OPERATOR-OWNED: operators select from the catalog in the admin UI.
 * seeded_tags  PLATFORM-OWNED: generated by this module; not editable by operators.
 *
 * Both draw from the same 30-tag controlled catalog (SEARCH_TAG_GROUPS in
 * src/lib/searchTags.ts). Only catalog-valid strings are ever produced here.
 *
 * V1 GENERATION SOURCES
 * ─────────────────────
 * Source A — Google Places metadata:
 *   outdoor_seating          → "Patio"
 *   live_music               → "Live Music"
 *   good_for_watching_sports → "Sports Viewing"
 *   good_for_children        → "Family Friendly"
 *   good_for_groups          → "Group Friendly"
 *   allows_dogs              → "Dog Friendly"
 *   serves_vegetarian_food   → "Vegetarian Friendly"
 *
 *   Rule: a tag is generated only when the column is explicitly TRUE.
 *   NULL (= unknown) and FALSE never generate a tag.
 *
 * Source B — HH specials:
 *   Food tags generated from hh_food_details ONLY:
 *     Wings · Burgers · Tacos · Seafood · Steak · Appetizers
 *   Drink tags generated from hh_drink_details ONLY:
 *     Wine · Cocktails
 *
 *   Strict field isolation prevents food items from generating drink tags
 *   (e.g., "shrimp cocktail" in food specials must not produce Cocktails).
 *
 * V2+ DEFERRED TAGS
 * ─────────────────
 * Craft Beer, Local Beer, Pizza, Small Plates, Mocktails, Gluten Friendly.
 * These need refined matching rules before reliable generation is possible.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Input type
// ─────────────────────────────────────────────────────────────────────────────

/**
 * The venue fields required to generate Seeded Tags.
 * All boolean fields from Google Places metadata default to null (unknown).
 */
export type SeededTagInput = {
  // Google Places discovery metadata (migration 031)
  outdoor_seating: boolean | null;
  live_music: boolean | null;
  good_for_watching_sports: boolean | null;
  good_for_children: boolean | null;
  good_for_groups: boolean | null;
  allows_dogs: boolean | null;
  serves_vegetarian_food: boolean | null;
  // HH specials
  hh_food_details: string | null;
  hh_drink_details: string | null;
};

// ─────────────────────────────────────────────────────────────────────────────
// Keyword rules
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Patterns applied to hh_food_details items only.
 * NEVER applied to drink items — prevents cross-contamination false positives.
 *
 * Deferred tags (Pizza, Small Plates, etc.) are not listed here.
 */
const FOOD_TAG_RULES: Array<{ tag: string; pattern: RegExp }> = [
  { tag: "Wings",      pattern: /\bwings?\b/i },
  { tag: "Burgers",    pattern: /\bburgers?\b|\bsliders?\b/i },
  { tag: "Tacos",      pattern: /\btacos?\b/i },
  {
    tag: "Seafood",
    pattern:
      /\bfish\b|\bprawns?\b|\bshrimps?\b|\bmussels?\b|\boysters?\b|\bcalamari\b|\bseafood\b|\bclams?\b|\bcrab\b|\blobster\b|\bscallops?\b/i,
  },
  { tag: "Steak",      pattern: /\bsteak\b|\bbeef dip\b|\bprime rib\b/i },
  {
    tag: "Appetizers",
    pattern: /\bappies?\b|\bappetizers?\b|\bnachos\b|\bfries\b|\bonion rings?\b/i,
  },
];

/**
 * Patterns applied to hh_drink_details items only.
 * NEVER applied to food items — prevents false positives like:
 *   - "shrimp cocktail" → Cocktails
 *   - "caesar salad"    → Cocktails
 *
 * "caesar" is intentionally excluded (caesar salad false positive).
 * "sparkling" is intentionally excluded (sparkling water false positive).
 * Deferred tags (Craft Beer, Local Beer, etc.) are not listed here.
 */
const DRINK_TAG_RULES: Array<{ tag: string; pattern: RegExp }> = [
  { tag: "Wine",      pattern: /\bwines?\b|\bprosecco\b|\bros[eé]\b/i },
  {
    tag: "Cocktails",
    pattern:
      /\bcocktails?\b|\bmargaritas?\b|\bmartinis?\b|\bmule\b|\bmojitos?\b|\bnegroni\b|\bold fashioned\b/i,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Specials text extractor
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Extracts item name strings from hh_food_details / hh_drink_details.
 *
 * Handles all three storage formats used in the DB:
 *   1. JSON object array  [{name, price?, notes?}]  — current admin format
 *   2. JSON string array  ["Wings — $8", ...]       — enrichment outputs
 *   3. Legacy pipe- or newline-split plain text      — pre-JSON imports
 *
 * Returns only the name portion of each item (price/notes stripped) so that
 * keyword matching doesn't accidentally match price strings or notes.
 *
 * Mirrors the structure of parseSpecials() in src/lib/data/venues.ts.
 * If that function's logic changes, update this one to stay in sync.
 */
export function extractSpecialsText(raw: string | null | undefined): string[] {
  if (!raw?.trim()) return [];

  // ── JSON path ────────────────────────────────────────────────────────────
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const items = JSON.parse(raw) as any[];
    if (!Array.isArray(items)) return splitByDelimiter(raw);

    return items
      .filter((it) => it != null)
      .map((it): string => {
        if (typeof it === "string") return it.trim();
        // Object item: use only the name field for matching
        if (typeof it === "object" && it.name) return String(it.name).trim();
        return "";
      })
      .filter(Boolean);
  } catch {
    return splitByDelimiter(raw);
  }
}

function splitByDelimiter(raw: string): string[] {
  const delimiter = raw.includes("|") ? "|" : "\n";
  return raw.split(delimiter).map((s) => s.trim()).filter(Boolean);
}

// ─────────────────────────────────────────────────────────────────────────────
// Main generator
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generates Seeded Tags for a venue from Google metadata and HH specials.
 *
 * Returns a deduplicated, sorted array of tag strings drawn from the
 * controlled catalog. Returns an empty array when no signals are found.
 *
 * @example
 *   generateSeededTags({
 *     outdoor_seating: true,
 *     live_music: null,
 *     ...,
 *     hh_food_details: '[{"name":"Wings","price":"11"}]',
 *     hh_drink_details: '[{"name":"House Wine","price":"8"}]',
 *   });
 *   // → ["Patio", "Wine", "Wings"]
 */
export function generateSeededTags(venue: SeededTagInput): string[] {
  const tags = new Set<string>();

  // ── Source A: Google metadata ────────────────────────────────────────────
  // Only generate a tag when the value is explicitly TRUE (not null/false).
  if (venue.outdoor_seating === true)          tags.add("Patio");
  if (venue.live_music === true)               tags.add("Live Music");
  if (venue.good_for_watching_sports === true) tags.add("Sports Viewing");
  if (venue.good_for_children === true)        tags.add("Family Friendly");
  if (venue.good_for_groups === true)          tags.add("Group Friendly");
  if (venue.allows_dogs === true)              tags.add("Dog Friendly");
  if (venue.serves_vegetarian_food === true)   tags.add("Vegetarian Friendly");

  // ── Source B: HH food specials (food rules only, never drink) ────────────
  const foodItems = extractSpecialsText(venue.hh_food_details);
  for (const item of foodItems) {
    for (const { tag, pattern } of FOOD_TAG_RULES) {
      if (pattern.test(item)) {
        tags.add(tag);
      }
    }
  }

  // ── Source B: HH drink specials (drink rules only, never food) ───────────
  const drinkItems = extractSpecialsText(venue.hh_drink_details);
  for (const item of drinkItems) {
    for (const { tag, pattern } of DRINK_TAG_RULES) {
      if (pattern.test(item)) {
        tags.add(tag);
      }
    }
  }

  return [...tags].sort();
}
