import { createAdminClient } from "@/lib/supabase/server";
import { getAllMarkets, getCitiesByMarket, getNeighbourhoodsByCity } from "@/lib/geo/geography";
import type { MarketRecord, CityRecord, NeighbourhoodRecord } from "@/lib/geo/types";

/**
 * Data helpers for the Content Engine (content_guides table).
 *
 * See docs/website/CONTENT_ENGINE_PRODUCT_SPEC.md. Card 1 added the list
 * read (getContentGuides). Card 2 adds the single-record read used by the
 * edit form (getContentGuideById). Create/update writes live in
 * app/control-panel/content-engine/actions.ts, following the actions.ts
 * convention used by discover/ and platform-admins/.
 *
 * Internal-only table (no RLS policies for anon/authenticated) — always
 * queried via createAdminClient() (service-role).
 */

// ── Types ──────────────────────────────────────────────────────────────────────

export type GuideType = "venue_guide" | "event_guide";

/**
 * Card 7 simplified this from the original four-state model
 * (draft/scheduled/published/expired) down to two — see
 * docs/website/CONTENT_ENGINE_PRODUCT_SPEC.md and the Card 7 task.
 * Scheduling and expiry are no longer part of the V1 editorial workflow;
 * an editor moves a guide from Draft to Published manually, and Discover
 * Management controls whether it's actually merchandised anywhere.
 *
 * The DB CHECK constraint (migration 052) still technically permits
 * 'scheduled'/'expired' — deliberately left as-is rather than migrated,
 * since the app no longer writes those values and narrowing the
 * constraint isn't necessary to get the simplification's benefit. Any
 * pre-existing row in one of those legacy states is normalized to
 * "draft" on read — see normalizeGuideStatus() below.
 */
export type GuideStatus = "draft" | "published";

/**
 * Coerces a raw DB status value into the current two-state model. Legacy
 * 'scheduled' guides become drafts (they were never public). Legacy
 * 'expired' guides also become drafts — they were already excluded from
 * public rendering under the old model too, since isGuidePublicNow() only
 * ever treated status === 'published' as public, so this preserves their
 * existing (non-)visibility exactly.
 */
export function normalizeGuideStatus(status: string): GuideStatus {
  return status === "published" ? "published" : "draft";
}

export type ContentGuideRow = {
  id: string;
  guide_type: GuideType;
  status: GuideStatus;
  title: string;
  slug: string;
  marketName: string | null;
  cityName: string | null;
  publish_at: string | null;
  updated_at: string;
};

/** Full row shape used by the create/edit form (raw FK ids, not joined names). */
export type ContentGuideDetail = {
  id: string;
  guide_type: GuideType;
  status: GuideStatus;
  market_id: string;
  city_id: string;
  neighbourhood_id: string | null;
  title: string;
  slug: string;
  primary_keyword: string | null;
  secondary_keywords: string[];
  intro: string | null;
  body: string | null;
  hero_image_url: string | null;
  publish_at: string | null;
  expire_at: string | null;
  // SEO fields (Card 4) — generated by the editor from guide inputs, or
  // admin-overridden. See src/lib/seo/contentGuideSeo.ts. All nullable so
  // guides created before migration 054 continue to load fine.
  page_title: string | null;
  meta_title: string | null;
  meta_description: string | null;
  og_title: string | null;
  og_description: string | null;
  canonical_url: string | null;
  created_at: string;
  updated_at: string;
};

// ── Queries ───────────────────────────────────────────────────────────────────

/** Returns all content guides, newest-updated first, for the Content Engine list page. */
export async function getContentGuides(): Promise<ContentGuideRow[]> {
  const supabase = createAdminClient();

  const { data, error } = await supabase
    .from("content_guides")
    .select(
      "id, guide_type, status, title, slug, publish_at, updated_at, " +
        "market:markets(name), city:cities(name)"
    )
    .order("updated_at", { ascending: false });

  if (error) {
    console.error("[getContentGuides]", error.message);
    return [];
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (data ?? []).map((row: Record<string, any>) => ({
    id:          row.id as string,
    guide_type:  row.guide_type as GuideType,
    status:      normalizeGuideStatus(row.status as string),
    title:       row.title as string,
    slug:        row.slug as string,
    marketName:  (row.market?.name as string | undefined) ?? null,
    cityName:    (row.city?.name as string | undefined) ?? null,
    publish_at:  row.publish_at as string | null,
    updated_at:  row.updated_at as string,
  }));
}

/** Returns a single guide by id, or null if not found — used by the edit form. */
export async function getContentGuideById(id: string): Promise<ContentGuideDetail | null> {
  const supabase = createAdminClient();

  const { data, error } = await supabase
    .from("content_guides")
    .select(
      "id, guide_type, status, market_id, city_id, neighbourhood_id, title, slug, " +
        "primary_keyword, secondary_keywords, intro, body, hero_image_url, " +
        "publish_at, expire_at, " +
        "page_title, meta_title, meta_description, og_title, og_description, canonical_url, " +
        "created_at, updated_at"
    )
    .eq("id", id)
    .maybeSingle();

  if (error) {
    console.error("[getContentGuideById]", error.message);
    return null;
  }
  if (!data) return null;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const row = data as Record<string, any>;

  return {
    id:                 row.id as string,
    guide_type:         row.guide_type as GuideType,
    status:             normalizeGuideStatus(row.status as string),
    market_id:          row.market_id as string,
    city_id:            row.city_id as string,
    neighbourhood_id:   row.neighbourhood_id as string | null,
    title:              row.title as string,
    slug:               row.slug as string,
    primary_keyword:    row.primary_keyword as string | null,
    secondary_keywords: (row.secondary_keywords as string[] | null) ?? [],
    intro:              row.intro as string | null,
    body:               row.body as string | null,
    hero_image_url:     row.hero_image_url as string | null,
    publish_at:         row.publish_at as string | null,
    expire_at:          row.expire_at as string | null,
    page_title:         (row.page_title as string | null) ?? null,
    meta_title:         (row.meta_title as string | null) ?? null,
    meta_description:   (row.meta_description as string | null) ?? null,
    og_title:           (row.og_title as string | null) ?? null,
    og_description:     (row.og_description as string | null) ?? null,
    canonical_url:      (row.canonical_url as string | null) ?? null,
    created_at:         row.created_at as string,
    updated_at:         row.updated_at as string,
  };
}

// ── Geography options for the guide form ────────────────────────────────────
// Reuses the Geography Data Foundation helpers (src/lib/geo/geography.ts).
// Market/city/neighbourhood counts are small, so all three levels are loaded
// upfront and filtered client-side by GuideForm — no per-selection round trip.

export type GuideFormGeography = {
  markets: MarketRecord[];
  cities: CityRecord[];
  neighbourhoods: NeighbourhoodRecord[];
};

/** Returns all markets, cities, and neighbourhoods for the guide form's location selects. */
export async function getGuideFormGeography(): Promise<GuideFormGeography> {
  const markets = await getAllMarkets();
  const citiesByMarket = await Promise.all(markets.map((m) => getCitiesByMarket(m.id)));
  const cities = citiesByMarket.flat();
  const neighbourhoodsByCity = await Promise.all(cities.map((c) => getNeighbourhoodsByCity(c.id)));
  const neighbourhoods = neighbourhoodsByCity.flat();

  return { markets, cities, neighbourhoods };
}

// ── Public guide read (Card 5) ───────────────────────────────────────────────
// Powers the public /{market}/guides/{guide-slug} route. Unlike the CP reads
// above, this only ever returns a guide that is actually public right now —
// status must be 'published' AND (if set) publish_at/expire_at must put the
// current moment inside the publish window. This is a read-time predicate,
// not scheduling automation: nothing here flips a guide's stored status: it
// just declines to render a guide whose own fields say it isn't public yet
// (or not anymore), which "Only render guides that are published / public"
// requires beyond a bare status check.

/** Guide shape for public rendering — includes resolved market/city/neighbourhood names. */
export type PublicGuideDetail = {
  id: string;
  guide_type: GuideType;
  title: string;
  slug: string;
  primary_keyword: string | null;
  secondary_keywords: string[];
  intro: string | null;
  body: string | null;
  hero_image_url: string | null;
  publish_at: string | null;
  updated_at: string;
  marketSlug: string;
  marketName: string;
  cityName: string | null;
  neighbourhoodName: string | null;
  page_title: string | null;
  meta_title: string | null;
  meta_description: string | null;
  og_title: string | null;
  og_description: string | null;
  canonical_url: string | null;
};

/**
 * The single source of truth for "is this guide actually public right now."
 * status must be 'published' AND (if set) publish_at/expire_at must put the
 * current moment inside the window. Shared by every public/merchandising
 * read (guide detail, guides library, homepage rail) so publish-window
 * logic is never duplicated — see Card 6B Part 5.
 */
export function isGuidePublicNow(
  status: string,
  publishAt: string | null,
  expireAt: string | null
): boolean {
  if (status !== "published") return false;
  const now = Date.now();
  if (publishAt && new Date(publishAt).getTime() > now) return false;
  if (expireAt && new Date(expireAt).getTime() <= now) return false;
  return true;
}

/**
 * Returns a published, in-window guide by market slug + guide slug, or null
 * if it doesn't exist, isn't published, or is outside its publish/expire
 * window. Guide slugs are unique per market (not globally), matching the
 * /{market}/guides/{slug} URL — see migration 052.
 */
export async function getPublicGuideByMarketAndSlug(
  marketSlug: string,
  guideSlug: string
): Promise<PublicGuideDetail | null> {
  const supabase = createAdminClient();

  const { data, error } = await supabase
    .from("content_guides")
    .select(
      "id, guide_type, status, title, slug, primary_keyword, secondary_keywords, " +
        "intro, body, hero_image_url, publish_at, expire_at, updated_at, " +
        "page_title, meta_title, meta_description, og_title, og_description, canonical_url, " +
        "markets!inner(slug, name), city:cities(name), neighbourhood:neighbourhoods(name)"
    )
    .eq("markets.slug", marketSlug)
    .eq("slug", guideSlug)
    .eq("status", "published")
    .maybeSingle();

  if (error || !data) return null;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const row = data as Record<string, any>;

  const publishAt = (row.publish_at as string | null) ?? null;
  const expireAt = (row.expire_at as string | null) ?? null;
  if (!isGuidePublicNow(row.status as string, publishAt, expireAt)) return null;

  const market = (row.markets as Record<string, unknown>) ?? {};
  const city = (row.city as Record<string, unknown> | null) ?? null;
  const neighbourhood = (row.neighbourhood as Record<string, unknown> | null) ?? null;

  return {
    id: row.id as string,
    guide_type: row.guide_type as GuideType,
    title: row.title as string,
    slug: row.slug as string,
    primary_keyword: (row.primary_keyword as string | null) ?? null,
    secondary_keywords: (row.secondary_keywords as string[] | null) ?? [],
    intro: row.intro as string | null,
    body: row.body as string | null,
    hero_image_url: row.hero_image_url as string | null,
    publish_at: publishAt,
    updated_at: row.updated_at as string,
    marketSlug: (market.slug as string) ?? marketSlug,
    marketName: (market.name as string) ?? "",
    cityName: (city?.name as string | undefined) ?? null,
    neighbourhoodName: (neighbourhood?.name as string | undefined) ?? null,
    page_title: (row.page_title as string | null) ?? null,
    meta_title: (row.meta_title as string | null) ?? null,
    meta_description: (row.meta_description as string | null) ?? null,
    og_title: (row.og_title as string | null) ?? null,
    og_description: (row.og_description as string | null) ?? null,
    canonical_url: (row.canonical_url as string | null) ?? null,
  };
}

/** Other published guides in the same market, for a lightweight "More Guides" cross-link section. */
export type RelatedGuideSummary = {
  title: string;
  slug: string;
  guide_type: GuideType;
  hero_image_url: string | null;
};

/**
 * Safe, minimal "related guides" query: other published guides in the same
 * market, newest-published first. This is NOT the Content Engine's curated
 * Related Guides feature from the product spec (admin-selected, searchable
 * dropdown) — that requires editor UI that hasn't been built. This is just
 * same-market published guides, queryable from fields that already exist,
 * so the public page can offer further reading without inventing new schema
 * or admin curation.
 */
export async function getRelatedGuides(
  marketSlug: string,
  excludeGuideId: string,
  limit = 3
): Promise<RelatedGuideSummary[]> {
  const supabase = createAdminClient();

  const { data, error } = await supabase
    .from("content_guides")
    .select("title, slug, guide_type, hero_image_url, publish_at, markets!inner(slug)")
    .eq("markets.slug", marketSlug)
    .eq("status", "published")
    .neq("id", excludeGuideId)
    .order("publish_at", { ascending: false, nullsFirst: false })
    .limit(limit);

  if (error) {
    console.error("[getRelatedGuides]", error.message);
    return [];
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (data ?? []).map((row: Record<string, any>) => ({
    title: row.title as string,
    slug: row.slug as string,
    guide_type: row.guide_type as GuideType,
    hero_image_url: (row.hero_image_url as string | null) ?? null,
  }));
}
