import type { MetadataRoute } from "next";
import { getSiteUrl, shouldNoIndex } from "@/lib/siteUrl";

/**
 * Dynamic robots.txt — generated by Next.js at /robots.txt.
 *
 * Staging / noindex environments:
 *   User-agent: *
 *   Disallow: /
 *
 * Production:
 *   User-agent: *
 *   Allow: /
 *   Disallow: /admin, /control-panel, /api/, /auth/
 *   Sitemap: https://happyhourcompass.com/sitemap.xml
 *
 * The staging block is controlled by NEXT_PUBLIC_NOINDEX=true in Vercel env settings.
 * Never set that env var on the production Vercel environment.
 *
 * Routes NOT in the disallow list (intentionally indexable):
 *   /               consumer home
 *   /venue/*        venue detail pages
 *   /event/*        event detail pages
 *   /explore        search / discovery
 *   /events         event listing
 *   /contact        contact form
 *   /privacy        privacy policy
 *   /terms          terms of service
 *   /suggest/*      add-your-business / suggest flows
 *
 * Routes blocked (private / internal / auth-required):
 *   /admin          operator admin shell
 *   /control-panel  founder control panel
 *   /api/           all API routes
 *   /auth/          Supabase auth callback
 *   /dashboard      deprecated redirect (was /admin)
 *   /login          auth page — no crawl value
 *   /forgot-password, /activate-account, /operator — auth flows
 */
export default function robots(): MetadataRoute.Robots {
  if (shouldNoIndex()) {
    return {
      rules: {
        userAgent: "*",
        disallow: "/",
      },
    };
  }

  const siteUrl = getSiteUrl();

  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/admin",
          "/admin/",
          "/control-panel",
          "/control-panel/",
          "/api/",
          "/auth/",
          "/dashboard",
          "/login",
          "/forgot-password",
          "/activate-account",
          "/operator",
          "/cp-invite",
          "/control-panel-login",
        ],
      },
    ],
    sitemap: `${siteUrl}/sitemap.xml`,
  };
}
