-- =============================================================================
-- Migration: 032_venues_seeded_tags.sql
--
-- Adds seeded_tags TEXT[] to the venues table.
--
-- OWNERSHIP MODEL
-- ───────────────
-- search_tags  — OPERATOR-OWNED: operators select from the controlled catalog
--                via the Operator Admin UI. Subject to plan limits.
-- seeded_tags  — PLATFORM-OWNED: generated by HHC from discovery metadata and
--                HH content. Operators do NOT see or edit this field. No
--                operator UI action can influence seeded_tags.
--
-- GENERATION SOURCES (V1)
-- ───────────────────────
-- Source A — Google Places discovery metadata (migration 031 columns):
--   outdoor_seating          → "Patio"
--   live_music               → "Live Music"
--   good_for_watching_sports → "Sports Viewing"
--   good_for_children        → "Family Friendly"
--   good_for_groups          → "Group Friendly"
--   allows_dogs              → "Dog Friendly"
--   serves_vegetarian_food   → "Vegetarian Friendly"
--
--   Rule: only when the column is explicitly TRUE. NULL (unknown) and FALSE
--   do not generate a tag.
--
-- Source B — HH specials content:
--   Food tags from hh_food_details ONLY (never from hh_drink_details):
--     Wings · Burgers · Tacos · Seafood · Steak · Appetizers
--   Drink tags from hh_drink_details ONLY (never from hh_food_details):
--     Wine · Cocktails
--
-- DEFERRED TO V2+
-- ───────────────
-- Craft Beer, Local Beer, Pizza, Small Plates, Mocktails, Gluten Friendly —
-- matching rules need refinement before these can be reliably generated.
-- See investigation findings in docs/seeded-tags-analysis.md.
--
-- TAG CATALOG
-- ───────────
-- seeded_tags values are drawn from the same controlled catalog as search_tags
-- (src/lib/searchTags.ts). Only catalog-valid strings should be stored here.
-- The application layer enforces this; no DB-level constraint is added so that
-- catalog expansions do not require schema changes.
--
-- BACKFILL
-- ────────
-- Run from operator-admin/:
--   npm run backfill:seeded-tags          ← dry-run (no DB writes)
--   npm run backfill:seeded-tags -- --apply  ← write to Supabase
--
-- The backfill script (scripts/backfillSeededTags.ts) is safe to rerun.
-- It regenerates seeded_tags from current venue data on every run.
-- =============================================================================

ALTER TABLE venues
  ADD COLUMN IF NOT EXISTS seeded_tags TEXT[] NOT NULL DEFAULT '{}';

COMMENT ON COLUMN public.venues.seeded_tags IS
  'Platform-generated discovery tags. Values drawn from the same controlled '
  'catalog as search_tags (src/lib/searchTags.ts). PLATFORM-OWNED — operators '
  'do NOT edit this field. Generated from Google Places metadata and HH '
  'specials content by scripts/backfillSeededTags.ts. '
  'See search_tags for the operator-managed equivalent.';
